name: Update images with latest release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sample-images branch
        uses: actions/checkout@v4
        with:
          ref: sample-images

      - name: Download latest release
        run: |
          response=$(curl -s https://api.github.com/repos/negset/Firple/releases/latest)
          asset_urls=$(echo $response | jq -r '.assets[] | .browser_download_url')
          wget asset_urls

      - name: Install fonts
        run: |
          unzip '*.zip'
          sudo mv Firple*.ttf /usr/share/fonts/ && fc-cache -fv

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Set up svg-to-webp
        run: |
          git clone https://github.com/negset/svg-to-webp.git
          cd svg-to-webp
          npm install

      - name: Create WebPs
        run: node svg-to-webp *.svg

      - name: Commit and push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add *.webp
          git commit -m "update images" || echo "No changes to commit"
          git push origin sample-images